# Copyright (c) 2026 C. Klukas. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Generate ckVision's pinned Unicode 15.1.0 property tables and the official
# extended-grapheme-cluster conformance cases. This script deliberately reads
# only the published UCD text files named below; it neither downloads data nor
# depends on a third-party Unicode library.
"""Generate checked-in Unicode 15.1.0 artifacts for ckVision."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


VERSION = "15.1.0"
INPUT_FILES = (
    "GraphemeBreakProperty.txt",
    "emoji-data.txt",
    "EastAsianWidth.txt",
    "DerivedCoreProperties.txt",
    "GraphemeBreakTest.txt",
)
GCB_PROPERTIES = (
    "CR",
    "LF",
    "Control",
    "Extend",
    "ZWJ",
    "Regional_Indicator",
    "Prepend",
    "SpacingMark",
    "L",
    "V",
    "T",
    "LV",
    "LVT",
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_ranges(path: Path, wanted: set[str]) -> dict[str, list[tuple[int, int]]]:
    ranges = {name: [] for name in wanted}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.partition("#")[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        property_name = "; ".join(fields[1:])
        if len(fields) < 2 or property_name not in wanted:
            continue
        start_end = fields[0].split("..")
        start = int(start_end[0], 16)
        end = int(start_end[-1], 16)
        ranges[property_name].append((start, end))
    return {name: coalesce(entries) for name, entries in ranges.items()}


def coalesce(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    if not ranges:
        return []
    ranges.sort()
    result = [ranges[0]]
    for start, end in ranges[1:]:
        previous_start, previous_end = result[-1]
        if start <= previous_end + 1:
            result[-1] = (previous_start, max(previous_end, end))
        else:
            result.append((start, end))
    return result


def cpp_identifier(property_name: str) -> str:
    return "k" + "".join(part.capitalize() for part in property_name.split("_"))


def cxx_bytes(text: str) -> str:
    encoded = text.encode("utf-8")
    return '"' + "".join(f"\\x{byte:02X}" for byte in encoded) + '"'


def generate_tables(input_dir: Path, output: Path, hashes: dict[str, str]) -> None:
    gcb = parse_ranges(input_dir / "GraphemeBreakProperty.txt", set(GCB_PROPERTIES))
    emoji = parse_ranges(input_dir / "emoji-data.txt", {"Extended_Pictographic"})
    eaw = parse_ranges(input_dir / "EastAsianWidth.txt", {"W", "F"})
    incb = parse_ranges(input_dir / "DerivedCoreProperties.txt", {"InCB; Consonant", "InCB; Linker", "InCB; Extend"})

    # DerivedCoreProperties uses a two-level property spelling in the UCD;
    # retain the generated public identifiers independently of that spelling.
    tables: list[tuple[str, list[tuple[int, int]]]] = [
        *( (cpp_identifier(name), gcb[name]) for name in GCB_PROPERTIES ),
        ("kExtendedPictographic", emoji["Extended_Pictographic"]),
        ("kEastAsianWide", coalesce(eaw["W"] + eaw["F"])),
        ("kIncbConsonant", incb["InCB; Consonant"]),
        ("kIncbLinker", incb["InCB; Linker"]),
        ("kIncbExtend", incb["InCB; Extend"]),
    ]

    lines = [
        "// Copyright (c) 2026 C. Klukas. All rights reserved.",
        "//",
        f"// Generated by tools/unicode/generate_unicode_tables.py from Unicode {VERSION} UCD files.",
        "// Input SHA-256:",
        *(f"//   {name}: {hashes[name]}" for name in INPUT_FILES[:-1]),
        "// Do not edit by hand; see docs/text-width.md for regeneration instructions.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "namespace ckv::text::unicode_15_1 {",
        "",
        "struct Range {",
        "    char32_t first;",
        "    char32_t last;",
        "};",
        "",
    ]
    for name, ranges in tables:
        lines.append(f"inline constexpr Range {name}[] = {{")
        for start, end in ranges:
            lines.append(f"    {{0x{start:04X}, 0x{end:04X}}},")
        lines.extend(("};", ""))
    lines.extend(("}  // namespace ckv::text::unicode_15_1", ""))
    output.write_text("\n".join(lines), encoding="utf-8")


def parse_break_test(path: Path) -> list[tuple[str, str]]:
    cases: list[tuple[str, str]] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        body = raw_line.partition("#")[0].strip()
        if not body:
            continue
        tokens = body.split()
        markers: list[str] = []
        codepoints: list[int] = []
        for token in tokens:
            if token in ("÷", "×"):
                markers.append(token)
            else:
                codepoints.append(int(token, 16))
        if len(markers) != len(codepoints) + 1:
            raise ValueError(f"unexpected GraphemeBreakTest line: {raw_line}")
        text = "".join(chr(cp) for cp in codepoints)
        # One ASCII marker per scalar, marking the boundary after it.
        breaks = "".join("1" if marker == "÷" else "0" for marker in markers[1:])
        cases.append((text, breaks))
    return cases


def generate_break_tests(input_dir: Path, output: Path, hashes: dict[str, str]) -> None:
    cases = parse_break_test(input_dir / "GraphemeBreakTest.txt")
    lines = [
        "// Copyright (c) 2026 C. Klukas. All rights reserved.",
        "//",
        f"// Generated from Unicode {VERSION} GraphemeBreakTest.txt.",
        f"// Input SHA-256: {hashes['GraphemeBreakTest.txt']}",
        "// Do not edit by hand; see docs/text-width.md for regeneration instructions.",
        "",
    ]
    for text, breaks in cases:
        lines.append(f"    {{{cxx_bytes(text)}, \"{breaks}\"}},")
    lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--tables", type=Path, required=True)
    parser.add_argument("--grapheme-tests", type=Path, required=True)
    args = parser.parse_args()

    missing = [name for name in INPUT_FILES if not (args.input_dir / name).is_file()]
    if missing:
        parser.error("missing required Unicode input files: " + ", ".join(missing))
    hashes = {name: sha256(args.input_dir / name) for name in INPUT_FILES}
    args.tables.parent.mkdir(parents=True, exist_ok=True)
    args.grapheme_tests.parent.mkdir(parents=True, exist_ok=True)
    generate_tables(args.input_dir, args.tables, hashes)
    generate_break_tests(args.input_dir, args.grapheme_tests, hashes)


if __name__ == "__main__":
    main()
