# Copyright (c) 2026 C. Klukas. All rights reserved.
# SPDX-License-Identifier: MIT
include_guard(GLOBAL)

# Inspect PE/COFF image bytes, not filenames or the configure host's CPU.
# This routine never executes an image and is also usable in cross-host gates.
function(ckvision_conpty_check_binary image architecture kind)
    if(NOT EXISTS "${image}" OR IS_DIRECTORY "${image}")
        message(FATAL_ERROR "ConPTY runtime image is missing: ${image}")
    endif()
    file(SIZE "${image}" size)
    if(size LESS 64)
        message(FATAL_ERROR "ConPTY runtime image has no complete DOS header: ${image}")
    endif()
    file(READ "${image}" magic LIMIT 2 HEX)
    if(NOT magic STREQUAL "4d5a")
        message(FATAL_ERROR "ConPTY runtime image is not PE/COFF: ${image}")
    endif()
    file(READ "${image}" offset OFFSET 60 LIMIT 4 HEX)
    string(SUBSTRING "${offset}" 0 2 b0)
    string(SUBSTRING "${offset}" 2 2 b1)
    string(SUBSTRING "${offset}" 4 2 b2)
    string(SUBSTRING "${offset}" 6 2 b3)
    math(EXPR pe_offset "0x${b3}${b2}${b1}${b0}")
    math(EXPR end "${pe_offset} + 24")
    if(pe_offset LESS 64 OR end GREATER size)
        message(FATAL_ERROR "ConPTY runtime image has an invalid PE offset: ${image}")
    endif()
    file(READ "${image}" signature OFFSET ${pe_offset} LIMIT 6 HEX)
    if(architecture STREQUAL "x86")
        set(expected "504500004c01")
    elseif(architecture STREQUAL "x64")
        set(expected "504500006486")
    elseif(architecture STREQUAL "arm64")
        set(expected "5045000064aa")
    else()
        message(FATAL_ERROR "ConPTY runtime architecture is unsupported: ${architecture}")
    endif()
    if(NOT signature STREQUAL expected)
        message(FATAL_ERROR "ConPTY runtime image architecture mismatch: ${image}; expected ${architecture}")
    endif()
    math(EXPR flags_offset "${pe_offset} + 22")
    file(READ "${image}" flags OFFSET ${flags_offset} LIMIT 2 HEX)
    string(SUBSTRING "${flags}" 0 2 f0)
    string(SUBSTRING "${flags}" 2 2 f1)
    math(EXPR executable "0x${f1}${f0} & 2")
    math(EXPR dll "0x${f1}${f0} & 8192")
    if(NOT executable OR (kind STREQUAL "DLL" AND NOT dll) OR
       (kind STREQUAL "EXE" AND dll) OR NOT kind MATCHES "^(DLL|EXE)$")
        message(FATAL_ERROR "ConPTY runtime image kind mismatch: ${image}; expected ${kind}")
    endif()
endfunction()
