# Copyright (c) 2026 C. Klukas. All rights reserved.
# SPDX-License-Identifier: MIT
if(NOT DEFINED CKV_CONPTY_MANIFEST OR NOT DEFINED CKV_CONPTY_IMAGE)
    message(FATAL_ERROR "ConPTY deployment requires its exact manifest and application image")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/CkVisionConptyBinary.cmake")
include("${CKV_CONPTY_MANIFEST}")
file(SHA256 "${CKV_CONPTY_ARCHIVE}" archive_hash)
if(NOT archive_hash STREQUAL CKV_CONPTY_SHA256)
    message(FATAL_ERROR "ConPTY deployment package SHA256 mismatch after configuration")
endif()
ckvision_conpty_check_binary("${CKV_CONPTY_IMAGE}" "${CKV_CONPTY_ARCHITECTURE}" EXE)
get_filename_component(output "${CKV_CONPTY_IMAGE}" DIRECTORY)
list(LENGTH CKV_CONPTY_FILES count)
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    list(GET CKV_CONPTY_FILES ${index} source)
    list(GET CKV_CONPTY_PATHS ${index} relative)
    get_filename_component(directory "${output}/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(COPY_FILE "${source}" "${output}/${relative}" ONLY_IF_DIFFERENT)
    file(SHA256 "${source}" expected)
    file(SHA256 "${output}/${relative}" actual)
    if(NOT expected STREQUAL actual)
        message(FATAL_ERROR "ConPTY deployment output does not match its package: ${relative}")
    endif()
endforeach()
