# Copyright (c) 2026 C. Klukas. All rights reserved.
# SPDX-License-Identifier: MIT
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/CkVisionConptyBinary.cmake")

# Explicit, optional deployment: no downloads and no mandatory runtime.
function(ckvision_deploy_conpty)
    cmake_parse_arguments(PARSE_ARGV 0 ckv "" "TARGET;ARCHIVE;SHA256;ARCHITECTURE;INSTALL_DESTINATION" "")
    if(ckv_UNPARSED_ARGUMENTS OR ckv_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "ckvision_deploy_conpty: unknown arguments or missing values")
    endif()
    foreach(required IN ITEMS TARGET ARCHIVE SHA256 ARCHITECTURE INSTALL_DESTINATION)
        if(NOT DEFINED ckv_${required} OR "${ckv_${required}}" STREQUAL "")
            message(FATAL_ERROR "ckvision_deploy_conpty requires ${required}")
        endif()
    endforeach()
    if(NOT TARGET "${ckv_TARGET}")
        message(FATAL_ERROR "ckvision_deploy_conpty requires an existing executable target")
    endif()
    get_target_property(kind "${ckv_TARGET}" TYPE)
    get_target_property(imported "${ckv_TARGET}" IMPORTED)
    get_target_property(alias "${ckv_TARGET}" ALIASED_TARGET)
    if(NOT kind STREQUAL "EXECUTABLE" OR imported OR alias)
        message(FATAL_ERROR "ckvision_deploy_conpty requires a build-owned, non-alias executable")
    endif()
    get_target_property(target_directory "${ckv_TARGET}" BINARY_DIR)
    if(NOT target_directory STREQUAL CMAKE_CURRENT_BINARY_DIR)
        message(FATAL_ERROR "ckvision_deploy_conpty must be called where its executable target is defined")
    endif()
    if(NOT WIN32)
        message(FATAL_ERROR "ckvision_deploy_conpty requires a Windows target platform")
    endif()
    string(TOLOWER "${ckv_ARCHITECTURE}" architecture)
    if(NOT architecture MATCHES "^(x86|x64|arm64)$")
        message(FATAL_ERROR "ckvision_deploy_conpty architecture must be x86, x64 or arm64")
    endif()
    if(NOT IS_ABSOLUTE "${ckv_ARCHIVE}" OR NOT EXISTS "${ckv_ARCHIVE}" OR IS_DIRECTORY "${ckv_ARCHIVE}")
        message(FATAL_ERROR "ckvision_deploy_conpty requires an absolute existing package archive")
    endif()
    string(LENGTH "${ckv_SHA256}" hash_length)
    if(NOT hash_length EQUAL 64 OR NOT ckv_SHA256 MATCHES "^[0-9A-Fa-f]+$")
        message(FATAL_ERROR "ckvision_deploy_conpty requires an explicit SHA256 package pin")
    endif()
    if(IS_ABSOLUTE "${ckv_INSTALL_DESTINATION}" OR
       ckv_INSTALL_DESTINATION MATCHES "(^|[/\\])[.][.]([/\\]|$)" OR
       ckv_INSTALL_DESTINATION MATCHES "[;$<>]")
        message(FATAL_ERROR "ckvision_deploy_conpty requires a relative contained install destination")
    endif()
    file(SHA256 "${ckv_ARCHIVE}" actual_hash)
    string(TOLOWER "${ckv_SHA256}" expected_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "ckvision_deploy_conpty package SHA256 mismatch")
    endif()
    get_target_property(deployed "${ckv_TARGET}" CKVISION_CONPTY_DEPLOYMENT)
    if(deployed)
        message(FATAL_ERROR "ckvision_deploy_conpty already configured for ${ckv_TARGET}")
    endif()
    string(SHA256 target_key "${ckv_TARGET}")
    # Keep normal Windows build paths comfortably below MAX_PATH. Refuse a
    # namespace collision rather than trusting a shortened name silently.
    string(SUBSTRING "${target_key}" 0 16 directory_key)
    set(target_stage "${CMAKE_CURRENT_BINARY_DIR}/ckvision-conpty/${directory_key}")
    if(EXISTS "${target_stage}/target.txt")
        file(READ "${target_stage}/target.txt" staged_target)
        if(NOT staged_target STREQUAL ckv_TARGET)
            message(FATAL_ERROR "ConPTY deployment target namespace collision")
        endif()
    endif()
    file(MAKE_DIRECTORY "${target_stage}")
    file(WRITE "${target_stage}/target.txt" "${ckv_TARGET}")
    # A changed pin gets a fresh extraction namespace. Reusing the old one
    # could let an omitted payload survive from a previous package.
    set(stage "${target_stage}/${actual_hash}")
    file(MAKE_DIRECTORY "${stage}/package")
    file(ARCHIVE_EXTRACT INPUT "${ckv_ARCHIVE}" DESTINATION "${stage}/package")
    set(nuspec "${stage}/package/Microsoft.Windows.Console.ConPTY.nuspec")
    if(NOT EXISTS "${nuspec}")
        message(FATAL_ERROR "ckvision_deploy_conpty package metadata is missing")
    endif()
    file(READ "${nuspec}" metadata)
    if(NOT metadata MATCHES "<id>Microsoft[.]Windows[.]Console[.]ConPTY</id>" OR
       NOT metadata MATCHES "<license type=\"expression\">MIT</license>" OR
       NOT metadata MATCHES "<version>([a-zA-Z0-9.+-]+)</version>")
        message(FATAL_ERROR "ckvision_deploy_conpty requires the official MIT ConPTY package metadata")
    endif()
    # Preserve the version match separately: compound condition evaluation may
    # replace CMAKE_MATCH_1 with an unrelated match.
    string(REGEX MATCH "<version>([a-zA-Z0-9.+-]+)</version>" version_match "${metadata}")
    set(version "${CMAKE_MATCH_1}")
    set(runtime_files "${stage}/package/runtimes/win-${architecture}/native/conpty.dll")
    set(runtime_paths conpty.dll)
    ckvision_conpty_check_binary("${runtime_files}" "${architecture}" DLL)
    # Microsoft selects its console host by the OS architecture, not the app
    # architecture. x64 emulation on ARM64 therefore needs BOTH native hosts.
    if(architecture STREQUAL "x86")
        set(hosts x86 x64 arm64)
    elseif(architecture STREQUAL "x64")
        set(hosts x64 arm64)
    else()
        set(hosts arm64)
    endif()
    foreach(host IN LISTS hosts)
        set(image "${stage}/package/build/native/runtimes/${host}/OpenConsole.exe")
        ckvision_conpty_check_binary("${image}" "${host}" EXE)
        list(APPEND runtime_files "${image}")
        list(APPEND runtime_paths "${host}/OpenConsole.exe")
    endforeach()
    set(module_directory "${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
    list(APPEND runtime_files "${module_directory}/Microsoft.ConPTY.LICENSE.txt")
    list(APPEND runtime_paths Microsoft.ConPTY.LICENSE.txt)
    set(manifest "${stage}/deployment.cmake")
    # Bracket strings keep backslashes, spaces, quotes and dollar signs literal.
    set(contents "set(CKV_CONPTY_ARCHITECTURE ${architecture})\n")
    string(APPEND contents "set(CKV_CONPTY_ARCHIVE [=[${ckv_ARCHIVE}]=])\nset(CKV_CONPTY_SHA256 ${actual_hash})\n")
    string(APPEND contents "set(CKV_CONPTY_FILES)\nset(CKV_CONPTY_PATHS)\n")
    list(LENGTH runtime_files count)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        list(GET runtime_files ${index} source)
        list(GET runtime_paths ${index} destination)
        set(delimiter "=")
        string(FIND "${source}" "]${delimiter}]" closing_at)
        while(NOT closing_at EQUAL -1)
            string(APPEND delimiter "=")
            string(FIND "${source}" "]${delimiter}]" closing_at)
        endwhile()
        string(APPEND contents "list(APPEND CKV_CONPTY_FILES [${delimiter}[${source}]${delimiter}])\n")
        string(APPEND contents "list(APPEND CKV_CONPTY_PATHS \"${destination}\")\n")
        get_filename_component(subdirectory "${destination}" DIRECTORY)
        install(FILES "${source}" DESTINATION "${ckv_INSTALL_DESTINATION}/${subdirectory}")
    endforeach()
    set(record "${stage}/Microsoft.ConPTY.Runtime.json")
    file(WRITE "${record}" "{\"package\":\"Microsoft.Windows.Console.ConPTY\",\"version\":\"${version}\",\"sha256\":\"${actual_hash}\",\"architecture\":\"${architecture}\"}\n")
    string(APPEND contents "list(APPEND CKV_CONPTY_FILES [=[${record}]=])\nlist(APPEND CKV_CONPTY_PATHS Microsoft.ConPTY.Runtime.json)\n")
    file(WRITE "${manifest}" "${contents}")
    install(FILES "${record}" DESTINATION "${ckv_INSTALL_DESTINATION}")
    set(copy_command "${CMAKE_COMMAND}" "-DCKV_CONPTY_MANIFEST=${manifest}"
        "-DCKV_CONPTY_IMAGE=$<TARGET_FILE:${ckv_TARGET}>"
        -P "${module_directory}/CkVisionConptyCopy.cmake")
    add_custom_command(TARGET "${ckv_TARGET}" POST_BUILD COMMAND ${copy_command} VERBATIM)
    # POST_BUILD alone does not refresh a runtime when only the archive changes
    # and the application is already linked. An ALL target checks/copies again.
    add_custom_target("ckv_conpty_${directory_key}" ALL COMMAND ${copy_command}
        DEPENDS "${ckv_TARGET}" "${ckv_ARCHIVE}" VERBATIM)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ckv_ARCHIVE}")
    set_property(TARGET "${ckv_TARGET}" PROPERTY CKVISION_CONPTY_DEPLOYMENT "${actual_hash}")
endfunction()
